version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ehm

  admin:
    image: adminer
    ports:
      - 8080:8080
